export const CONTACT_SUCCESS = 'CONTACTS_LOAD_SUCCESS';
export const CONTACT_FAILED = 'CONTACTS_LOAD_FAILED';

export const CONTACT_CREATED = 'CONTACT_CREATED';
export const CONTACT_CREATE_FAILED = 'CONTACT_CREATE_FAILED';