export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const USERINFOSUCCESS = 'USERINFOSUCCESS';
export const USERINFOFAILED = 'USERINFOFAILED';